# Phase 1 — Why NumPy Exists

Normal Python lists are slow for mathematical computation.

Example:

In [1]:
a = [1, 2, 3]
b = [4, 5, 6]

result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)

[5, 7, 9]


Works.

But NumPy does this MUCH faster and cleaner.

## Your First NumPy Program
Install? No need in Colab

Already installed.

### Notebook Cell 1

In [2]:
import numpy as np


`np` is just an alias.

Industry standard:

pandas → pd
numpy → np
matplotlib → plt

## Creating Your First Array

### Notebook Cell 2

In [4]:
arr=np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Important:

NumPy arrays are called `ndarray`
They are optimized for numerical computation

## Python List vs NumPy Array

### Notebook Cell 3

In [5]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

print(type(python_list))
print(type(numpy_array))

<class 'list'>
<class 'numpy.ndarray'>


## Why NumPy is Powerful
### Vectorized Operations

Instead of loops:

In [6]:
arr = np.array([1, 2, 3])

print(arr + 10)

[11 12 13]


Output:

`[11 12 13]`

Every element got updated automatically.

This is called:

**Vectorization**

VERY IMPORTANT for ML.

### Practice 1

Try these yourself:

In [7]:
arr = np.array([2, 4, 6, 8])

print(arr * 2)
print(arr ** 2)
print(arr // 2)

[ 4  8 12 16]
[ 4 16 36 64]
[1 2 3 4]


Predict output before running.

## Dimensions in NumPy

This is THE MOST IMPORTANT CONCEPT.

### 1D Array

In [9]:
arr = np.array([1, 2, 3])

Looks like:

`[1 2 3]`

Dimension = 1

### 2D Array

In [11]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)
arr2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

Think:

rows
columns

Exactly like datasets.

### Shape

#### Notebook Cell

In [12]:
print(arr2.shape)

(2, 3)


Meaning:

2 rows
3 columns

VERY IMPORTANT in machine learning.

### ndim

In [13]:
print(arr2.ndim)

2


Meaning:
2-dimensional array.

### size

In [15]:
print(arr2.size)

6


Total elements.

### dtype

In [16]:
print(arr2.dtype)

int64


Data type stored.

### Practice 2

Create this array:

`[[10, 20],
 [30, 40],
 [50, 60]]`

Then print:

shape
ndim
size
dtype

In [23]:
arr_practice = np.array([
    [10,20],
    [30,40],
    [50,60]
])
print(arr_practice)
print(arr_practice.dtype)
print(arr_practice.shape)
print(arr_practice.ndim)
print(arr_practice.size)

[[10 20]
 [30 40]
 [50 60]]
int64
(3, 2)
2
6


## Indexing in NumPy

Exactly like Python — but more powerful.

### 1D Indexing

In [ ]:
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[-1])

### 2D Indexing

In [26]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# in python arr2[0][0]
# but here in numpy
print(arr2[0,0])
print(arr2[1,-1])

1
6


Format:

`[row, column]`

### Slicing

#### 1D

In [30]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:])
print(arr[1:])
print(arr[:2])

[20 30 40]
[10 20 30 40 50]
[20 30 40 50]
[10 20]


#### 2D Slicing

In [33]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr2[:, 1])   # : means all rows but 1 column
print(arr2[-1,:])   # means last row but all columns
# (:) means take everything
print(arr2[:])

[2 5 8]
[7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Meaning:

all rows
column index 1
SUPER IMPORTANT
:

Means:
“take everything”

### Practice 3

From this array:

`arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])`

Try extracting:

first row
second column
last two rows
middle element

In [42]:
arr_practice3 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# first row
print("First row: ", arr_practice3[0])

# second column
print("Second column: ", arr_practice3[:,1])

# last two rows
print("Last two rows: ", arr_practice3[1:])

# middle element
print("Middle Element: ", arr_practice3[1,1])

First row:  [10 20 30]
Second column:  [20 50 80]
Last two rows:  [[40 50 60]
 [70 80 90]]
Middle Element:  50


## Built-in Array Creation Functions

You’ll use these constantly.

### zeros()

In [44]:
np.zeros((3, 4))

# this means three rows and 4 columns all zeros initilazitation same in the next as ones
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Creates:

`[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]`

### ones()

In [45]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### arange()

Like Python range.

In [50]:
# this is interesting its like range function in python but creates array from that range
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace()

VERY IMPORTANT in ML and plotting.

In [53]:
# it will create evenly space from a to b and how many c spaces
np.linspace(0, 1, 5)
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

Meaning:
5 evenly spaced values between 0 and 1.

## Reshaping Arrays

CRITICAL FOR MACHINE LEARNING.

### reshape()

In [58]:
arr = np.arange(1, 13)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Now reshape:

In [59]:
# it will reconstruct the 1d array to our desired row and column array but we have to be precise mathematically
arr = arr.reshape(3, 4)

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Important Rule

Total elements must match.

12 elements can become:

3×4
2×6
4×3

But NOT 5×5.

### Practice 4

Create:

`[1 to 20]`

Then reshape into:

4×5
2×10

In [64]:
# i did a mistake i type arrange but it is arange actually
arr_practice4=np.arange(1,21)
print("Original array before reshape: ", arr_practice4)

# now we are applying reshape
print(arr_practice4.reshape((4,5)))
print(arr_practice4.reshape((2,10)))


Original array before reshape:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


## Mathematical Operations

In [65]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


Element-wise operations.

## Aggregation Functions

VERY IMPORTANT for Data Science.

### sum()

In [66]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # Re-initialize arr for context
print(arr.sum())

21


### mean()

In [67]:
print(arr.mean())

3.5


### max()

In [68]:
print(arr.max())

6


### min()

In [69]:
print(arr.min())

1


### std()

Standard deviation:

In [70]:
print(arr.std())

1.707825127659933


Used heavily in ML preprocessing.

## axis Concept (VERY IMPORTANT)
### Example

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

### Column-wise Sum

In [74]:
# arr.sum(axis=0) is for columns wise sum and axis=1 is for row wise sum
print(arr.sum(axis=0))

[5 7 9]


### Row-wise Sum

In [73]:
print(arr.sum(axis=1))

[ 6 15]


## Broadcasting (Most Important Intermediate Concept)

This is where beginners struggle.

### Example

In [75]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr + 10)

[[11 12 13]
 [14 15 16]]


NumPy automatically broadcasts 10 across all elements.

### Another Example

In [76]:
# the trick is that treat b as a whole and this whole b is doing operation on each element of a irrespective of the length of b
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([10, 20, 30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [82]:
# one more example
a=np.array([
    [1,2,3],
    [4,3,2],
    [3,4,3]
])
b=np.array([2,7,9])
print(a+b)
# c=np.array([3,4])
# print(a+c) this will produce error that shapes cant be broadcasted together

d=np.array([5])
print(a+d)  # but this is working i think you have to use some common sense also in broadcasting so you will get that concept very well



[[ 3  9 12]
 [ 6 10 11]
 [ 5 11 12]]
[[6 7 8]
 [9 8 7]
 [8 9 8]]


Study this output carefully.

This is REAL NumPy power.

## Random Module

SUPER IMPORTANT FOR ML.

### Random Numbers

In [83]:
np.random.rand(3)

array([0.28662612, 0.16537901, 0.66937121])

### Random Matrix

In [84]:
np.random.rand(2, 3)

array([[0.86619112, 0.02357355, 0.28910109],
       [0.21251945, 0.12226145, 0.33915886]])

### Random Integers

In [91]:
# as it is written 1 to 100 any number but size(3,3) means 3 rows and 3 columns array and values are generated randomly everytime we are running this
np.random.randint(1, 100, size=(3, 3))
# but we are getting new numbers everytime we run it if we want same output so everyone can use it we have to use seed

array([[75, 88, 24],
       [ 3, 22, 53],
       [ 2, 88, 30]])

In [95]:
np.random.seed(42)
np.random.randint(1,10, size=(2,2))

# now the output never changes so everyone got same numbers if i share the notebook

array([[7, 4],
       [8, 5]])

### Seed

IMPORTANT.

In [89]:
np.random.seed(42)

Makes random outputs reproducible.

Used heavily in ML experiments.

## Mini Data Science Example

Imagine student marks.

In [96]:
marks = np.array([80, 75, 90, 60, 85])

print("Average:", marks.mean())
print("Highest:", marks.max())
print("Lowest:", marks.min())

Average: 78.0
Highest: 90
Lowest: 60


This is literally how data analysis begins.

# Assignment 1: NumPy Fundamentals

### Tasks

1. **Task 1:** Create a 3×3 matrix.
2. **Task 2:** Print its shape.
3. **Task 3:** Extract the second row.
4. **Task 4:** Extract the third column.
5. **Task 5:** Multiply all elements by 5.
6. **Task 6:** Find the sum, mean, and max.
7. **Task 7:** Reshape a 1D array of 12 elements into a 3×4 matrix.
8. **Task 8:** Generate a random 4×4 matrix.

In [119]:
# task 1
arr = np.array([
    [1,6,7],
    [6,3,7],
    [8,4,2]
])

# task 2,3,4
print("Array shape: ",arr.shape)
print("Second row: ", arr[1])
print("Third Column: ",arr[:,2])

# task 5,6
print("Multiply by 5: ",arr*5)
print("Sum: ",arr.sum())
print("Mean: ",arr.mean())
print("Max: ",arr.max())

# task 7
new_arr=np.arange(1,13)
print("Reshaped arr: ",new_arr.reshape((3,4)))


# task 8
print("Random arr: ",np.random.randint(1,17, size=(4,4)))


Array shape:  (3, 3)
Second row:  [6 3 7]
Third Column:  [7 7 2]
Multiply by 5:  [[ 5 30 35]
 [30 15 35]
 [40 20 10]]
Sum:  44
Mean:  4.888888888888889
Max:  8
Reshaped arr:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Random arr:  [[11  5 10  7]
 [10  9 12  7]
 [ 9  8 12  2]
 [ 1 16  7  7]]


# Intermediate Level

## 1. Boolean Masking (EXTREMELY IMPORTANT)

This is how real datasets are filtered.

### Example

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)
# a this will return a python array of boolean if condition true then True else False.

[False False  True  True  True]


Output:

`[False False  True  True  True]`

NumPy checks every element individually.

This creates a:

**Boolean Mask**

### Using the Mask

In [2]:
print(arr[arr > 25])
# this syntax arr[arr>25] will return only those elements of that arr which satisfies the condition

[30 40 50]


Output:

`[30 40 50]`

This is HUGE in Data Science.

### Real Data Science Thinking

Imagine:

marks > 90
salary < 50000
age >= 18
missing values
filtering fraud transactions

Everything uses boolean masking.

### Practice

In [3]:
arr = np.array([5, 12, 18, 7, 25, 30])

# extract values greater than 15
print("Greater than 15:", arr[arr>15])

# extract even numbers
print("Even numbers:", arr[arr % 2 == 0])

# extract values less than 20
print("Less than 20:", arr[arr < 20])

Greater than 15: [18 25 30]
Even numbers: [12 18 30]
Less than 20: [ 5 12 18  7]


### Multiple Conditions

Use:

`&` → AND
`|` → OR

IMPORTANT:
Use parentheses.

#### Example

In [4]:
arr = np.array([10, 20, 30, 40, 50])

# we can use arr[(one condition) then & or | then (another condition)]
print("more than 20 but less than 50, ", arr[(arr>20) & (arr<50)])

more than 20 but less than 50,  [30 40]


Output:

`[30 40]`

### Common Beginner Mistake

WRONG:

`arr[arr > 20 and arr < 50]`

NumPy arrays cannot use Python's normal `and`.

Use:

`&`
`|`

## 2. Modifying Data with Conditions

Very common in preprocessing.

### Example

In [5]:
arr = np.array([10, 20, 30, 40, 50])

# this will assign the value where arr>30 to 999
arr[arr > 30] = 999

print(arr)

[ 10  20  30 999 999]


Output:

`[ 10  20  30 999 999]`

### Real ML Usage

Used for:

clipping outliers
replacing missing values
thresholding
image preprocessing

## 3. Fancy Indexing

Selecting multiple elements together.

### Example

In [7]:
# actually it is easy you just take any element from the arr without range it works without range
arr = np.array([10, 20, 30, 40, 50])

# here 0th , 2nd , and 4th element will pe printed
print(arr[[0, 2, 4]])

# we can make variable also like in any order or without variable in any order
indices=[4,2,3]
print(arr[indices])

[10 30 50]
[50 30 40]


Output:

`[10 30 50]`

### 2D Fancy Indexing

In [ ]:
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

# here it means 0th and 2nd row not 0 to 2nd because we are using [  []  ]
print(arr[[0, 2]])

Output:

`[[1 2]
 [5 6]]`

### Why Important?

Very common in:

train-test split
selecting rows
shuffling datasets

## 4. Broadcasting Deep Dive

This separates beginners from intermediate users.

### Example 1

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

vector = np.array([10, 20, 30])

print(arr + vector)

Output:

`[[11 22 33]
 [14 25 36]]`

### What Happened?

NumPy automatically expanded:

`[10 20 30]`

into:

`[[10 20 30]
 [10 20 30]]`

WITHOUT actually copying memory.

That’s broadcasting.

### Broadcasting Rules

Two dimensions are compatible if:

equal
OR
one of them is 1

### Example 2

In [ ]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([10, 20, 30])

print(a + b)

Output:

`[[11 21 31]
 [12 22 32]
 [13 23 33]]`

This is SUPER IMPORTANT.

### Visual Understanding

`a` shape:

`(3,1)`

`b` shape:

`(3,)`

Broadcasting creates virtual expansion.

### Broadcasting Error

In [9]:
# This code is expected to produce an error due to incompatible shapes for broadcasting.
# It's included here to demonstrate a broadcasting error as described in the text.
# a = np.array([1,2,3])
# b = np.array([1,2])
# print(a + b)

Error:
shapes incompatible.

## 5. Matrix Multiplication

CRITICAL FOR MACHINE LEARNING.

Linear regression.
Neural networks.
Deep learning.

Everything depends on this.

### Element-wise vs Matrix Multiplication
#### Element-wise

In [ ]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print(a * b)

Output:

`[[ 5 12]
 [21 32]]`

### REAL Matrix Multiplication

Use:

`@`

OR

`np.dot()`

#### Example

In [ ]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print(a @ b)

Output:

`[[19 22]
 [43 50]]`

In [12]:
# one more example of matrix multiplication where you can check shape also
# this a is 3*3
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# this b is 2*3
b=np.array([
    [1,7,8],
    [9,5,2]
])

# so after that 3*3 and 2*3 output must be 3*3
# this a @ b will give error because with this @ the no. of columns in a should be  equal to no. of rows in b and here it is not true
#print(a @ b)

# but if i do (b@a) it will work it satisfies the condition now
print(b @ a)

[[ 85 101 117]
 [ 43  59  75]]


### Why This Matters

Machine learning formula:

`y=XW+b`

That entire operation is matrix multiplication.

### Shape Rule for Matrix Multiplication

MOST IMPORTANT RULE:

`(m×n)(n×p)=(m×p)`

Inner dimensions must match.

#### Example

`(2×3) @ (3×4)`

Possible.

Result:

`(2×4)`

## 6. Transpose

Rows become columns.

### Example

In [ ]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.T)

Output:

`[[1 4]
 [2 5]
 [3 6]]`

### Why Important?

Used constantly in:

linear algebra
covariance
ML math
neural networks

## 7. Statistical Operations

Real preprocessing starts here.

### Example Dataset

In [13]:
data = np.array([10, 20, 30, 40, 50])

### Mean

In [14]:
print(data.mean())

30.0


### Standard Deviation

In [15]:
print(data.std())

14.142135623730951


### Variance

In [16]:
print(data.var())

200.0


### Median

In [17]:
print(np.median(data))

30.0


### Percentile

In [18]:
print(np.percentile(data, 90))

46.0


Very important in analytics.

## 8. Useful NumPy Functions
### unique()

In [19]:
arr = np.array([1,2,2,3,3,3])

print(np.unique(arr))

[1 2 3]


### sort()

In [20]:
print(np.sort(arr))

[1 2 2 3 3 3]


### concatenate()

In [21]:
a = np.array([1,2])
b = np.array([3,4])

print(np.concatenate((a,b)))

[1 2 3 4]


### where()

EXTREMELY IMPORTANT.

In [22]:
# they will return only indices if the condition is true
arr = np.array([10,20,30,40])

print(np.where(arr > 20))

(array([2, 3]),)


#### Conditional Replacement

In [23]:
arr = np.array([10,20,30,40])

# this is what we use a lot in classification problems the syntax means np.where(arr > 20 , 1, 0) if condition true change the value to 1 else 0
result = np.where(arr > 20, 1, 0)

print(result)

[0 0 1 1]


Output:

`[0 0 1 1]`

Used heavily in classification problems.

## 9. Real Dataset Style Example

Now let's think like data scientists.

### Student Scores Dataset

In [24]:
scores = np.array([
    [85, 90, 78],
    [60, 65, 70],
    [95, 88, 92],
    [40, 50, 45]
])

Columns:

Math
Science
English

Rows:

students

### Average Score Per Student

In [30]:
# axis 1 means by rows
print(np.round(scores.mean(axis=1),1))

[84.3 65.  91.7 45. ]


### Average Score Per Subject

In [31]:
print(scores.mean(axis=0))

[70.   73.25 71.25]


### Students with Average > 80

In [32]:
avg = scores.mean(axis=1)

# only those rows where average of those rows is greater than 80
print(scores[avg > 80])

[[85 90 78]
 [95 88 92]]


This is REAL dataset filtering.

### Normalize Data

VERY IMPORTANT IN ML.

Formula:

`z = (x - μ) / σ`

### NumPy Version

In [33]:
data = np.array([10,20,30,40,50])

# x means data that that data.mean() is mu and std is standard deviation of that data is normalization here
normalized = (data - data.mean()) / data.std()

print(normalized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


This is exactly what preprocessing pipelines do.

## What You Should Now Practice

You are entering the real NumPy zone now.

Practice:

masking
filtering
broadcasting
matrix multiplication
transpose
normalization
statistics

until they feel natural.

## Your Intermediate Assignment

Solve these on your own.

### Task 1

Create a random 5×5 matrix between 1–100.

In [35]:
# Task 1 Solution
matrix_5x5=np.random.randint(1,101, size=(5,5))
print("Random 5x5 matrix: \n", matrix_5x5)




Random 5x5 matrix: 
 [[68 32 70 15 53]
 [87 88 43  4 21]
 [91 87 80 29 31]
 [22 10 89 81 23]
 [90  8 86 20  1]]


Task 2

Extract:

values > 50
even values
values divisible by 5

In [36]:
# Task 2 Solution (using the matrix from Task 1)

# values > 50
print("\nValues greater than 50:", matrix_5x5[matrix_5x5>50])

# even values
print("\nEven values:", matrix_5x5[matrix_5x5 % 2 == 0])

# values divisible by 5
print("\nValues divisible by 5:", matrix_5x5[matrix_5x5 % 5 == 0])


Values greater than 50: [68 70 53 87 88 91 87 80 89 81 90 86]

Even values: [68 32 70 88  4 80 22 10 90  8 86 20]

Values divisible by 5: [70 15 80 10 90 20]


### Task 3

Replace all values < 30 with 0.

In [37]:
# Task 3 Solution (using the matrix from Task 1, make a copy to avoid modifying previous task output)
matrix_task3 = matrix_5x5.copy()
matrix_task3[matrix_task3 < 30] = 0
print("\nMatrix with values < 30 replaced by 0:\n", matrix_task3)


Matrix with values < 30 replaced by 0:
 [[68 32 70  0 53]
 [87 88 43  0  0]
 [91 87 80  0 31]
 [ 0  0 89 81  0]
 [90  0 86  0  0]]


### Task 4

Create two matrices:

(2×3)

and

(3×2)

Perform matrix multiplication.

In [38]:
# Task 4 Solution
matrix_2x3 = np.random.randint(1, 10, size=(2, 3))
matrix_3x2 = np.random.randint(1, 10, size=(3, 2))

print("\nMatrix (2x3):\n", matrix_2x3)
print("\nMatrix (3x2):\n", matrix_3x2)
print("\nMatrix Multiplication (2x3 @ 3x2):\n", matrix_2x3 @ matrix_3x2)


Matrix (2x3):
 [[6 7 5]
 [2 1 2]]

Matrix (3x2):
 [[7 6]
 [8 8]
 [7 7]]

Matrix Multiplication (2x3 @ 3x2):
 [[133 127]
 [ 36  34]]


### Task 5

Normalize this array:

`[10, 20, 30, 40, 50]`

using z-score normalization.

In [39]:
# Task 5 Solution
array_to_normalize = np.array([10, 20, 30, 40, 50])
mean_val = array_to_normalize.mean()
std_dev = array_to_normalize.std()

normalized_array = (array_to_normalize - mean_val) / std_dev
print("\nOriginal array:", array_to_normalize)
print("Normalized array (Z-score):", normalized_array)


Original array: [10 20 30 40 50]
Normalized array (Z-score): [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
